"""Bounded native-sequence search: Families A (VWAP band reversal),
B (VWAP acceptance continuation), C (EMA reversal), D (EMA continuation).
All candidates are NATIVE: generated by the sequence, not by an existing
structural recognizer. Development years only."""
from __future__ import annotations
import numpy as np, pickle, os, json, itertools, csv
from collections import defaultdict
exec(open("scripts/sequence_engine.py").read().split('if __name__')[0])

man=json.load(open(os.path.join(SEG,"manifest.json")))
SEGS=[]
for si in range(man["n_segments"]):
    fp=os.path.join(FEAT,f"feat_{si:03d}.pkl")
    if not os.path.exists(fp): continue
    D=pickle.load(open(fp,"rb"))
    if D.get("empty"): continue
    bars=pickle.load(open(os.path.join(SEG,f"seg{si:03d}.pkl"),"rb"))
    F=D["feat"]
    h=F["high"].astype(float); l=F["low"].astype(float); c=F["close"].astype(float)
    o=np.array([b.open for b in bars]); ts=[b.ts_et for b in bars]
    SEGS.append({"F":F,"h":h,"l":l,"c":c,"o":o,"ts":ts,"atr1":atr_wilder(h,l,c,24)})
print(f"segments in memory: {len(SEGS)}",flush=True)
WEEKS=None

def gen_A(S,cfg):
    F,c,h,l,o,ts,atr1=S["F"],S["c"],S["h"],S["l"],S["o"],S["ts"],S["atr1"]
    E=build_events(F,c,h,l,atr1,cfg["anchor"],cfg["band"])
    ema=F[f"ema21_{cfg['ema_tf']}"].astype(float) if cfg["ema_tf"] else None
    W=cfg["window"]; out=[]
    for ext_arr,rev_arr,d in ((E["ext_up"],E["rev_dn"],-1),(E["ext_dn"],E["rev_up"],+1)):
        ri=0
        for a in ext_arr:
            while ri<len(rev_arr) and rev_arr[ri]<=a: ri+=1
            if ri>=len(rev_arr): break
            b=rev_arr[ri]
            if b-a>W: continue
            conf=b
            if ema is not None:
                k=b; f=-1
                while k<min(len(c),b+cfg["ema_window"]+1):
                    if (d<0 and c[k]<ema[k]) or (d>0 and c[k]>ema[k]): f=k;break
                    k+=1
                if f<0: continue
                conf=f
            i=conf+1
            if i>=len(c)-1 or not(DEV[0]<=ts[i].year<=DEV[1]): continue
            extpx=(h[a:conf+1].max() if d<0 else l[a:conf+1].min())
            entry=o[i]; stop_d=max(abs(entry-extpx),atr1[i-1],MIN_STOP)
            stop=entry-stop_d if d>0 else entry+stop_d
            tm=cfg["target"]
            tgt=(E["vw"][i-1] if tm=="vwap" else entry+d*float(tm[:-1])*stop_d)
            if (d>0 and tgt<=entry) or (d<0 and tgt>=entry): continue
            if abs(tgt-entry)<atr1[i-1]: continue
            xt,p=simulate(h,l,o,i,d,stop,tgt)
            out.append((ts[i],ts[i].date(),d,p,stop_d,xt))
    return out

def gen_C(S,cfg):
    """EMA reversal: price extended >X ATR from EMA -> closes back through EMA
    -> next-bar entry toward EMA."""
    F,c,h,l,o,ts,atr1=S["F"],S["c"],S["h"],S["l"],S["o"],S["ts"],S["atr1"]
    ema=F[f"ema21_{cfg['ema_tf']}"].astype(float)
    thr=cfg["ext_atr"]; W=cfg["window"]; out=[]
    dist=(c-ema)/np.maximum(atr1,1e-9)
    above=dist>thr; below=dist<-thr
    for state,d in ((above,-1),(below,+1)):
        idx=np.flatnonzero(state[1:]&~state[:-1])+1
        for a in idx:
            f=-1
            for k in range(a+1,min(len(c),a+W+1)):
                if (d<0 and c[k]<ema[k]) or (d>0 and c[k]>ema[k]): f=k;break
            if f<0: continue
            i=f+1
            if i>=len(c)-1 or not(DEV[0]<=ts[i].year<=DEV[1]): continue
            extpx=(h[a:f+1].max() if d<0 else l[a:f+1].min())
            entry=o[i]; stop_d=max(abs(entry-extpx),atr1[i-1],MIN_STOP)
            stop=entry-stop_d if d>0 else entry+stop_d
            tm=cfg["target"]
            if tm=="vwap":
                tgt=F[f"vwap_{cfg['anchor']}"].astype(float)[i-1]
            else: tgt=entry+d*float(tm[:-1])*stop_d
            if (d>0 and tgt<=entry) or (d<0 and tgt>=entry): continue
            if abs(tgt-entry)<atr1[i-1]: continue
            xt,p=simulate(h,l,o,i,d,stop,tgt)
            out.append((ts[i],ts[i].date(),d,p,stop_d,xt))
    return out

def evaluate(rows):
    rows.sort(key=lambda z:z[0])
    ch=[];until=None
    for r in rows:
        if until is not None and r[0]<until: continue
        ch.append(r); until=r[0]+__import__("pandas").Timedelta(minutes=1)
    return ch

def metrics(ch):
    if len(ch)<200: return None
    days=(ch[-1][1]-ch[0][1]).days or 1; wk=days/7
    o={"trades":len(ch),"per_week":len(ch)/wk}
    for cost in (0.0,1.0,2.0):
        r=np.array([(x[3]-cost)/x[4] for x in ch])
        pos=r[r>0].sum(); neg=-r[r<=0].sum()
        eq=np.cumsum(r); yv=defaultdict(float)
        for x,v in zip(ch,r): yv[x[1].year]+=v
        t=f"{cost:g}"
        o[f"pf{t}"]=float(pos/neg) if neg>0 else 0.0
        o[f"net{t}"]=float(r.sum()); o[f"mdd{t}"]=float((eq-np.maximum.accumulate(eq)).min())
        o[f"posyr{t}"]=int(sum(1 for v in yv.values() if v>0))
    return o

ANCH=["GLOBEX_1800","MIDNIGHT_0000","LONDON_0300","CASH_0930","TEN_1000","NYPM_1330"]
res=[];cid=0
for anchor in ANCH:
  for band in (1,2,3):
    for window in (5,15):
      for ema_tf in (None,1,5):
        for target in ("vwap","1R","2R"):
          cid+=1
          cfg={"anchor":anchor,"band":band,"window":window,"ema_tf":ema_tf,
               "ema_window":5,"target":target}
          rows=[]
          for S in SEGS: rows.extend(gen_A(S,cfg))
          m=metrics(evaluate(rows))
          rec={"config_id":f"A{cid:05d}","family":"A_native","source":"NATIVE_SEQUENCE",
               "desc":f"VWAP({anchor}) {band}SD ext->revert(<={window}b)"
                      f"{'->EMA'+str(ema_tf)+'m cross' if ema_tf else ''} -> next bar, tgt={target}"}
          if m: rec.update(m)
          rec["status"]="EVALUATED" if m else "TOO_FEW"
          res.append(rec)
  print(f"  anchor {anchor} done, configs={cid}",flush=True)
for anchor in ANCH[:3]:
  for ema_tf in (1,5,15):
    for ext_atr in (1.0,2.0):
      for window in (5,15):
        for target in ("vwap","1R","2R"):
          cid+=1
          cfg={"anchor":anchor,"ema_tf":ema_tf,"ext_atr":ext_atr,"window":window,"target":target}
          rows=[]
          for S in SEGS: rows.extend(gen_C(S,cfg))
          m=metrics(evaluate(rows))
          rec={"config_id":f"C{cid:05d}","family":"C_native","source":"NATIVE_SEQUENCE",
               "desc":f"px >{ext_atr}ATR from EMA21({ema_tf}m) -> close back through (<={window}b)"
                      f" -> next bar, tgt={target}, vwapref={anchor}"}
          if m: rec.update(m)
          rec["status"]="EVALUATED" if m else "TOO_FEW"
          res.append(rec)
print(f"total native configs: {cid}",flush=True)
json.dump(res,open(os.path.join(OUT,"native_results.json"),"w"),default=str)
ev=[r for r in res if r["status"]=="EVALUATED"]
print(f"evaluated: {len(ev)}")
ev.sort(key=lambda r:-r["pf1"])
print(f"\n{'config':<8}{'desc':<74}{'n':>6}{'/wk':>6}{'PF1':>8}{'PF2':>8}{'py1':>5}")
for r in ev[:20]:
    print(f"{r['config_id']:<8}{r['desc'][:73]:<74}{r['trades']:>6}{r['per_week']:>6.1f}"
          f"{r['pf1']:>8.4f}{r['pf2']:>8.4f}{r['posyr1']:>4}/8")
surv=[r for r in ev if r["posyr1"]==8 and r["pf1"]>=1.15 and r["trades"]>=500 and r["per_week"]>=1.5]
print(f"\nNATIVE 8/8 SURVIVORS (PF@1>=1.15, >=500 trades, >=1.5/wk): {len(surv)}")
for r in surv: print(f"   {r['config_id']} {r['desc'][:70]} PF1={r['pf1']:.4f} PF2={r['pf2']:.4f}")
